### ISSUE TITLE
Question: Does hashed_unique index support heterogeneous lookup

### ISSUE THREAD

**Issue by void-mian** [boostorg/multi_index#79]
The STL support heterogeneous lookup in c++20 (example: https://en.cppreference.com/w/cpp/container/unordered_map/find). And after reading through multi_index::hashed_unique's find implement, I feel that multi_index already support it natively?

**Comment by joaquintides** [comment]
Yes, heterengeous lookup is supported in hashed (and ordered) indices:

https://www.boost.org/libs/multi_index/doc/reference/hash_indices.html#lookup

There are differences with respect to how this is supported in the standard:

* There's no need to mark the hash function and equality predicate as `is_transparent`; they are always assumed to be so.
* Additional lookup functions are provided where transparent hash and equality objects are passed to be used instead of those of the index proper. This is an extension with respect to the standard.

**Comment by void-mian** [comment]
Thanks for your patient and detailed answer.
